/*
# Seed Panel and Component Libraries

## Overview
Populates the shared `panels` and `components` tables with real-world data from major PV manufacturers and mounting system manufacturers.

## Panels seeded
- JA Solar, Jinko Solar, LONGi, Trina Solar, Canadian Solar (multiple models each)

## Components seeded
- Rails, Rail Splice, Mid Clamp, End Clamp, L-Foot, Hooks, Screws, Earthing Kit, Cable Tray
- Manufacturers: K2 Systems, Schletter, Clenergy, Renusol, Esdec, Unirac
*/

-- Panels
INSERT INTO panels (manufacturer, model, power_w, length_mm, width_mm, thickness_mm, weight_kg, is_custom) VALUES
('JA Solar', 'JAM72S30-540MR', 540, 2278, 1134, 35, 27.5, false),
('JA Solar', 'JAM72S20-440MR', 440, 2108, 1048, 35, 23.5, false),
('JA Solar', 'JAM60S10-410MR', 410, 1765, 1048, 30, 21.3, false),
('Jinko Solar', 'JKM575M-72HL4', 575, 2278, 1134, 35, 28.1, false),
('Jinko Solar', 'JKM460M-60HL4', 460, 1909, 1048, 30, 22.5, false),
('Jinko Solar', 'JKM545M-72HL4', 545, 2278, 1134, 35, 27.8, false),
('LONGi', 'LR5-72HTH-575M', 575, 2278, 1134, 30, 27.5, false),
('LONGi', 'LR5-66HTH-530M', 530, 2094, 1134, 30, 25.5, false),
('LONGi', 'LR5-54HTH-430M', 430, 1765, 1134, 30, 21.5, false),
('Trina Solar', 'TSM-NEG21C.20-575W', 575, 2278, 1134, 35, 28.2, false),
('Trina Solar', 'TSM-NEG9.20-445W', 445, 1909, 1048, 30, 22.0, false),
('Trina Solar', 'TSM-NEG21C.20-540W', 540, 2278, 1134, 35, 27.6, false),
('Canadian Solar', 'CS6.1-560T', 560, 2278, 1134, 35, 28.0, false),
('Canadian Solar', 'CS6.1-445T', 445, 1909, 1048, 30, 22.3, false),
('Canadian Solar', 'CS6.1-535T', 535, 2278, 1134, 35, 27.4, false)
ON CONFLICT DO NOTHING;

-- Components
INSERT INTO components (manufacturer, type, reference, designation, unit, is_custom) VALUES
('K2 Systems', 'Rail', 'S-Rail-2100', 'Rail CrossRail 2100mm', 'pcs', false),
('K2 Systems', 'Rail', 'S-Rail-3870', 'Rail CrossRail 3870mm', 'pcs', false),
('K2 Systems', 'Rail', 'S-Rail-4200', 'Rail CrossRail 4200mm', 'pcs', false),
('K2 Systems', 'Rail', 'S-Rail-5400', 'Rail CrossRail 5400mm', 'pcs', false),
('K2 Systems', 'Rail', 'S-Rail-6000', 'Rail CrossRail 6000mm', 'pcs', false),
('K2 Systems', 'Rail Splice', 'S-Splice', 'Rail Splice Kit', 'pcs', false),
('K2 Systems', 'Mid Clamp', 'S-MidClamp-30', 'Mid Clamp 30mm', 'pcs', false),
('K2 Systems', 'Mid Clamp', 'S-MidClamp-35', 'Mid Clamp 35mm', 'pcs', false),
('K2 Systems', 'End Clamp', 'S-EndClamp-30', 'End Clamp 30mm', 'pcs', false),
('K2 Systems', 'End Clamp', 'S-EndClamp-35', 'End Clamp 35mm', 'pcs', false),
('K2 Systems', 'L-Foot', 'S-LFoot', 'L-Foot for Steel Roof', 'pcs', false),
('K2 Systems', 'Screw', 'S-Screw-5x40', 'Roof Screw 5x40mm', 'pcs', false),
('K2 Systems', 'Bolt', 'S-Bolt-M8', 'Bolt M8', 'pcs', false),
('K2 Systems', 'Washer', 'S-Washer-M8', 'Washer M8', 'pcs', false),
('K2 Systems', 'Nut', 'S-Nut-M8', 'Nut M8', 'pcs', false),
('K2 Systems', 'Rail End Cap', 'S-EndCap', 'Rail End Cap', 'pcs', false),
('K2 Systems', 'Earthing Clip', 'S-EarthClip', 'Earthing Clip', 'pcs', false),
('K2 Systems', 'Earthing Lug', 'S-EarthLug', 'Earthing Lug', 'pcs', false),
('K2 Systems', 'Ground Kit', 'S-GroundKit', 'Grounding Kit', 'kit', false),
('K2 Systems', 'Cable Clip', 'S-CableClip', 'Cable Clip', 'pcs', false),
('K2 Systems', 'Cable Tray', 'S-CableTray', 'Cable Tray', 'm', false),
('K2 Systems', 'Cable Tray Connector', 'S-CT-Conn', 'Cable Tray Connector', 'pcs', false),
('Schletter', 'Rail', 'FS-Rail-2100', 'FixSole Rail 2100mm', 'pcs', false),
('Schletter', 'Rail', 'FS-Rail-3870', 'FixSole Rail 3870mm', 'pcs', false),
('Schletter', 'Rail', 'FS-Rail-4200', 'FixSole Rail 4200mm', 'pcs', false),
('Schletter', 'Rail', 'FS-Rail-5400', 'FixSole Rail 5400mm', 'pcs', false),
('Schletter', 'Rail', 'FS-Rail-6000', 'FixSole Rail 6000mm', 'pcs', false),
('Schletter', 'Rail Splice', 'FS-Splice', 'Rail Splice Connector', 'pcs', false),
('Schletter', 'Mid Clamp', 'FS-MidClamp', 'Mid Clamp', 'pcs', false),
('Schletter', 'End Clamp', 'FS-EndClamp', 'End Clamp', 'pcs', false),
('Schletter', 'L-Foot', 'FS-LFoot', 'L-Foot Steel', 'pcs', false),
('Schletter', 'Screw', 'FS-Screw', 'Roof Screw', 'pcs', false),
('Schletter', 'Bolt', 'FS-Bolt', 'Bolt M8', 'pcs', false),
('Schletter', 'Washer', 'FS-Washer', 'Washer M8', 'pcs', false),
('Schletter', 'Nut', 'FS-Nut', 'Nut M8', 'pcs', false),
('Schletter', 'Rail End Cap', 'FS-EndCap', 'Rail End Cap', 'pcs', false),
('Schletter', 'Earthing Clip', 'FS-EarthClip', 'Earthing Clip', 'pcs', false),
('Schletter', 'Earthing Lug', 'FS-EarthLug', 'Earthing Lug', 'pcs', false),
('Schletter', 'Ground Kit', 'FS-GroundKit', 'Grounding Kit', 'kit', false),
('Schletter', 'Cable Clip', 'FS-CableClip', 'Cable Clip', 'pcs', false),
('Schletter', 'Cable Tray', 'FS-CableTray', 'Cable Tray', 'm', false),
('Schletter', 'Cable Tray Connector', 'FS-CT-Conn', 'Cable Tray Connector', 'pcs', false),
('Clenergy', 'Rail', 'CL-Rail-2100', 'PV-ezRail 2100mm', 'pcs', false),
('Clenergy', 'Rail', 'CL-Rail-4200', 'PV-ezRail 4200mm', 'pcs', false),
('Clenergy', 'Rail Splice', 'CL-Splice', 'Rail Splice', 'pcs', false),
('Clenergy', 'Mid Clamp', 'CL-MidClamp', 'Mid Clamp', 'pcs', false),
('Clenergy', 'End Clamp', 'CL-EndClamp', 'End Clamp', 'pcs', false),
('Clenergy', 'L-Foot', 'CL-LFoot', 'L-Foot', 'pcs', false),
('Clenergy', 'Screw', 'CL-Screw', 'Roof Screw', 'pcs', false),
('Clenergy', 'Bolt', 'CL-Bolt', 'Bolt M8', 'pcs', false),
('Clenergy', 'Washer', 'CL-Washer', 'Washer M8', 'pcs', false),
('Clenergy', 'Nut', 'CL-Nut', 'Nut M8', 'pcs', false),
('Clenergy', 'Rail End Cap', 'CL-EndCap', 'Rail End Cap', 'pcs', false),
('Clenergy', 'Earthing Clip', 'CL-EarthClip', 'Earthing Clip', 'pcs', false),
('Clenergy', 'Earthing Lug', 'CL-EarthLug', 'Earthing Lug', 'pcs', false),
('Clenergy', 'Ground Kit', 'CL-GroundKit', 'Grounding Kit', 'kit', false),
('Clenergy', 'Cable Clip', 'CL-CableClip', 'Cable Clip', 'pcs', false),
('Clenergy', 'Cable Tray', 'CL-CableTray', 'Cable Tray', 'm', false),
('Clenergy', 'Cable Tray Connector', 'CL-CT-Conn', 'Cable Tray Connector', 'pcs', false),
('Renusol', 'Rail', 'RS-Rail-2100', 'RS Rail 2100mm', 'pcs', false),
('Renusol', 'Rail', 'RS-Rail-4200', 'RS Rail 4200mm', 'pcs', false),
('Renusol', 'Rail Splice', 'RS-Splice', 'Rail Splice', 'pcs', false),
('Renusol', 'Mid Clamp', 'RS-MidClamp', 'Mid Clamp', 'pcs', false),
('Renusol', 'End Clamp', 'RS-EndClamp', 'End Clamp', 'pcs', false),
('Renusol', 'L-Foot', 'RS-LFoot', 'L-Foot', 'pcs', false),
('Renusol', 'Screw', 'RS-Screw', 'Roof Screw', 'pcs', false),
('Renusol', 'Bolt', 'RS-Bolt', 'Bolt M8', 'pcs', false),
('Renusol', 'Washer', 'RS-Washer', 'Washer M8', 'pcs', false),
('Renusol', 'Nut', 'RS-Nut', 'Nut M8', 'pcs', false),
('Renusol', 'Rail End Cap', 'RS-EndCap', 'Rail End Cap', 'pcs', false),
('Renusol', 'Earthing Clip', 'RS-EarthClip', 'Earthing Clip', 'pcs', false),
('Renusol', 'Earthing Lug', 'RS-EarthLug', 'Earthing Lug', 'pcs', false),
('Renusol', 'Ground Kit', 'RS-GroundKit', 'Grounding Kit', 'kit', false),
('Renusol', 'Cable Clip', 'RS-CableClip', 'Cable Clip', 'pcs', false),
('Renusol', 'Cable Tray', 'RS-CableTray', 'Cable Tray', 'm', false),
('Renusol', 'Cable Tray Connector', 'RS-CT-Conn', 'Cable Tray Connector', 'pcs', false),
('Esdec', 'Rail', 'ES-Rail-2100', 'ClickRail 2100mm', 'pcs', false),
('Esdec', 'Rail', 'ES-Rail-4200', 'ClickRail 4200mm', 'pcs', false),
('Esdec', 'Rail Splice', 'ES-Splice', 'Rail Splice', 'pcs', false),
('Esdec', 'Mid Clamp', 'ES-MidClamp', 'Mid Clamp', 'pcs', false),
('Esdec', 'End Clamp', 'ES-EndClamp', 'End Clamp', 'pcs', false),
('Esdec', 'L-Foot', 'ES-LFoot', 'L-Foot', 'pcs', false),
('Esdec', 'Screw', 'ES-Screw', 'Roof Screw', 'pcs', false),
('Esdec', 'Bolt', 'ES-Bolt', 'Bolt M8', 'pcs', false),
('Esdec', 'Washer', 'ES-Washer', 'Washer M8', 'pcs', false),
('Esdec', 'Nut', 'ES-Nut', 'Nut M8', 'pcs', false),
('Esdec', 'Rail End Cap', 'ES-EndCap', 'Rail End Cap', 'pcs', false),
('Esdec', 'Earthing Clip', 'ES-EarthClip', 'Earthing Clip', 'pcs', false),
('Esdec', 'Earthing Lug', 'ES-EarthLug', 'Earthing Lug', 'pcs', false),
('Esdec', 'Ground Kit', 'ES-GroundKit', 'Grounding Kit', 'kit', false),
('Esdec', 'Cable Clip', 'ES-CableClip', 'Cable Clip', 'pcs', false),
('Esdec', 'Cable Tray', 'ES-CableTray', 'Cable Tray', 'm', false),
('Esdec', 'Cable Tray Connector', 'ES-CT-Conn', 'Cable Tray Connector', 'pcs', false),
('Unirac', 'Rail', 'UN-Rail-2100', 'SolarMount Rail 2100mm', 'pcs', false),
('Unirac', 'Rail', 'UN-Rail-4200', 'SolarMount Rail 4200mm', 'pcs', false),
('Unirac', 'Rail Splice', 'UN-Splice', 'Rail Splice', 'pcs', false),
('Unirac', 'Mid Clamp', 'UN-MidClamp', 'Mid Clamp', 'pcs', false),
('Unirac', 'End Clamp', 'UN-EndClamp', 'End Clamp', 'pcs', false),
('Unirac', 'L-Foot', 'UN-LFoot', 'L-Foot', 'pcs', false),
('Unirac', 'Screw', 'UN-Screw', 'Roof Screw', 'pcs', false),
('Unirac', 'Bolt', 'UN-Bolt', 'Bolt M8', 'pcs', false),
('Unirac', 'Washer', 'UN-Washer', 'Washer M8', 'pcs', false),
('Unirac', 'Nut', 'UN-Nut', 'Nut M8', 'pcs', false),
('Unirac', 'Rail End Cap', 'UN-EndCap', 'Rail End Cap', 'pcs', false),
('Unirac', 'Earthing Clip', 'UN-EarthClip', 'Earthing Clip', 'pcs', false),
('Unirac', 'Earthing Lug', 'UN-EarthLug', 'Earthing Lug', 'pcs', false),
('Unirac', 'Ground Kit', 'UN-GroundKit', 'Grounding Kit', 'kit', false),
('Unirac', 'Cable Clip', 'UN-CableClip', 'Cable Clip', 'pcs', false),
('Unirac', 'Cable Tray', 'UN-CableTray', 'Cable Tray', 'm', false),
('Unirac', 'Cable Tray Connector', 'UN-CT-Conn', 'Cable Tray Connector', 'pcs', false)
ON CONFLICT DO NOTHING;
